[mcp_servers.chrome-devtools]
command = "nix-shell"
args = [ ".agents/skills/mcp-chrome-devtools/shell.nix", "--run", ".agents/skills/mcp-chrome-devtools/bin/serve",]
id = ""

[mcp_servers.chrome-devtools.env]
