/** Lazy Shiki syntax-highlighter for fenced code blocks. Browser-only and
 *  loaded on demand — a dynamic `import("shiki")` keeps Shiki + its grammars
 *  out of the initial bundle, so a markdown view that has no code never pays
 *  for it, and a view that does renders code plain for one frame, then
 *  re-highlights once the highlighter is warm.
 *
 *  Output is dual-theme (github-light + github-dark, emitted as CSS variables
 *  via `defaultColor:false`), so it follows the app's light/dark with no
 *  re-highlight — markdown.css swaps the active variable under `.dark`.
 *
 *  Shiki escapes the code text into the highlighted span tree, so its output
 *  is *trusted* markup the sanitize pass injects directly (the only untrusted
 *  input — the code text — never reaches the DOM unescaped). */

import type { Highlighter } from "shiki";

export const SHIKI_LIGHT = "github-light";
export const SHIKI_DARK = "github-dark";

// A curated language set, kept reasonable so the one-time grammar load stays
// cheap. An unlisted language falls back to plain `text` — still themed +
// boxed + copyable, just not colorized.
export const LANGS = [
  "javascript",
  "typescript",
  "jsx",
  "tsx",
  "json",
  "jsonc",
  "html",
  "xml",
  "css",
  "scss",
  "markdown",
  "bash",
  "shellscript",
  "python",
  "ruby",
  "go",
  "rust",
  "c",
  "cpp",
  "java",
  "kotlin",
  "swift",
  "php",
  "sql",
  "yaml",
  "toml",
  "ini",
  "docker",
  "diff",
  "graphql",
  "lua",
  "nix",
  "haskell",
  "elixir",
  "make",
  "perl",
] as const;

// Common info-string aliases → a grammar in LANGS.
export const ALIAS: Record<string, string> = {
  js: "javascript",
  mjs: "javascript",
  cjs: "javascript",
  ts: "typescript",
  sh: "bash",
  zsh: "bash",
  shell: "bash",
  console: "bash",
  py: "python",
  rb: "ruby",
  rs: "rust",
  golang: "go",
  "c++": "cpp",
  h: "c",
  hpp: "cpp",
  yml: "yaml",
  md: "markdown",
  dockerfile: "docker",
  kt: "kotlin",
  ex: "elixir",
};

const SUPPORTED = new Set<string>(LANGS);

let highlighter: Highlighter | null = null;
let loadPromise: Promise<Highlighter> | null = null;

/** Begin loading the singleton highlighter (idempotent). Resolves to it; a
 *  component awaits this and re-renders so `highlightCode` starts returning
 *  markup. */
export function loadHighlighter(): Promise<Highlighter> {
  if (!loadPromise) {
    loadPromise = (async () => {
      const { createHighlighter } = await import("shiki");
      highlighter = await createHighlighter({
        themes: [SHIKI_LIGHT, SHIKI_DARK],
        langs: [...LANGS],
      });
      return highlighter;
    })();
  }
  return loadPromise;
}

/** Highlight a fenced code block to trusted dual-theme HTML, or `undefined`
 *  when the highlighter isn't loaded yet (the caller then leaves the block
 *  plain). The returned string is `<pre class="shiki" …>` with inline color
 *  variables — generated by Shiki from escaped code text, hence trusted. */
export function highlightCode(code: string, lang: string): string | undefined {
  if (!highlighter) return undefined;
  const key = lang.toLowerCase();
  const resolved = ALIAS[key] ?? key;
  const useLang = SUPPORTED.has(resolved) ? resolved : "text";
  try {
    return highlighter.codeToHtml(code, {
      lang: useLang,
      themes: { light: SHIKI_LIGHT, dark: SHIKI_DARK },
      defaultColor: false,
    });
  } catch {
    return undefined;
  }
}
