# arivu-tui viewer — Bun-built tree (arivu P3 PR1).
#
# Produces $out/lib/arivu-tui ready to be exec'd by the `bun` wrapper in the
# repo-root `default.nix`. Co-located with the viewer it builds (this whole
# packages/arivu-tui/nix/ tree) so the package is self-contained. This is the
# one-level-up twin of drishti's Bun-on-Nix recipe (nix/packages/drishti-agent
# in srid/drishti): the dep cache comes from
# the committed `bun/bun.nix` via `bun2nix.fetchBunDeps` (per-tarball FODs, no
# network in the sandbox), and `@kolu/*` is HYDRATED from kolu's own source
# after `bun install`, never bun-installed.
#
# Why hydrate (not a bun workspace): the viewer reaches @kolu/arivu-contract,
# @kolu/surface and @kolu/surface-nix-host, and arivu-contract pulls in
# @kolu/terminal-awareness's ZOD-ONLY `/schema` entry. But terminal-awareness's
# full manifest declares anyagent/anyforge/kaval/kolu-* (node-pty and the whole
# sensor spine). A bun workspace would try to resolve that entire manifest;
# hydrating the SOURCE sidesteps it — only what the viewer actually imports at
# runtime matters, and the flat npm closure those sources resolve is declared in
# `bun/package.json`. This is exactly why drishti hydrates @kolu/surface too.
#
# `koluSrc` is kolu's shared `src` fileset (default.nix) — reused verbatim so
# this build's source closure matches the typecheck's, with no parallel fileset
# to drift. It carries packages/arivu-tui (the viewer) and the five hydrated
# @kolu packages.
{ stdenv, lib, bun, bun2nix, koluSrc }:
let
  # The Bun project root: the bun-facing manifest + lockfile + bunfig + the
  # autogenerated dep cache. Co-located with the viewer (./bun, beside this file)
  # but EXCLUDED from the pnpm workspace via pnpm-workspace.yaml's
  # `!packages/arivu-tui/nix/**` — so pnpm, whose workspace glob is packages/**,
  # never sees this second package.json (the two package managers never fight).
  src = lib.fileset.toSource {
    root = ./bun;
    fileset = lib.fileset.unions [
      ./bun/package.json
      ./bun/bun.lock
      ./bun/bunfig.toml
      ./bun/bun.nix
    ];
  };
  # The workspace closure to hydrate, as `package-name → source dir under
  # packages/`. This is the COMPLETE runtime set the viewer resolves under Bun,
  # established empirically (`bun src/bin.ts list` reaches its socket-connect
  # step with every module resolved): the @kolu/surface stack, plus the
  # vendor-neutral schema packages `@kolu/arivu-contract` composes
  # `AwarenessValue` from — `terminal-awareness/schema` pulls anyforge/kolu-git/
  # kolu-{github,claude-code,codex,opencode}'s `/schemas`, and those agent
  # schemas pull `anyagent`'s barrel. Each is reached only through a zod-only
  # `/schemas` (or anyagent's light index) entry, so their heavy `.` deps
  # (@anthropic SDK, simple-git, @parcel/watcher) never load — which is exactly
  # why hydrating the SOURCE beats a bun workspace that would resolve the whole
  # manifest. Integration packages live under packages/integrations/<dir> with a
  # name that differs from the dir, so this is a map, not a flat list.
  koluPackages = {
    "@kolu/arivu-contract" = "arivu-contract";
    "@kolu/surface" = "surface";
    "@kolu/surface-nix-host" = "surface-nix-host";
    "@kolu/terminal-awareness" = "terminal-awareness";
    "@kolu/shell-quote" = "shell-quote";
    "anyagent" = "integrations/anyagent";
    "anyforge" = "integrations/anyforge";
    "kolu-git" = "integrations/git";
    "kolu-github" = "integrations/github";
    "kolu-claude-code" = "integrations/claude-code";
    "kolu-codex" = "integrations/codex";
    "kolu-opencode" = "integrations/opencode";
  };
in
stdenv.mkDerivation (finalAttrs: {
  pname = "arivu-tui-built";
  version = "0.1.0";
  inherit src;

  # Our npins-pinned bun wins on PATH over bun2nix.hook's propagated bun, for a
  # reproducible install across linux-x64 and darwin-arm64 (drishti's rationale).
  nativeBuildInputs = [ bun bun2nix.hook ];

  bunDeps = bun2nix.fetchBunDeps {
    bunNix = ./bun/bun.nix;
  };

  # Hoisted linker matches bunfig.toml: the hydrated @kolu/* sources carry no
  # node_modules of their own, so they must resolve @orpc/*, zod and solid-js
  # from one root node_modules.
  #
  # `--backend=copyfile` forces real writable copies out of the read-only bun.nix
  # FOD cache. The default backend (macOS: clonefile) the sandbox can't always
  # take, so bun falls back to symlinking package dirs straight at the read-only
  # store — then a version-conflicting dep that needs a NESTED `node_modules`
  # (e.g. `babel-plugin-jsx-dom-expressions/node_modules/@babel/helper-module-imports`)
  # fails with `AccessDenied: Failed to open node_modules folder` because its
  # parent is read-only. Copying every package in makes the parent writable so the
  # nest lands. (Linux hardlinks into the writable build dir, so it never hit this;
  # copyfile is just slightly slower there — correctness over speed for one build.)
  bunInstallFlags = [ "--linker=hoisted" "--backend=copyfile" ];

  # Pure overhead for a Bun app — no shebangs we care about, no native binaries.
  dontFixup = true;
  dontPatchShebangs = true;

  # Drive `bun build.ts` ourselves instead of the bun2nix hook's build phase, so
  # the @opentui/solid plugin (not a runtime preload) does the JSX transform at
  # build time — see packages/arivu-tui/build.ts for why.
  dontUseBunBuild = true;

  # Bring the viewer source + its build script into the bun project root (deps
  # already populated above), then run `bun build.ts` to produce dist/bin.js — see
  # packages/arivu-tui/build.ts for what gets bundled vs left native and why.
  # `cp -L` because the store sources are read-only; build.ts only reads them, and
  # Bun.build writes dist/ into the writable build root.
  buildPhase = ''
    runHook preBuild
    cp -rL ${koluSrc}/packages/arivu-tui/src ./src
    cp -L ${koluSrc}/packages/arivu-tui/build.ts ./build.ts
    ${bun}/bin/bun build.ts
    runHook postBuild
  '';

  # @kolu/* are Nix-store sources, not bun.lock entries — drop them into
  # node_modules AFTER bun install populates it. cp -rL (not symlink): the
  # hydrated sources resolve their transitive imports from the *real* file
  # location, so they must sit at a path whose ancestor is the hoisted root
  # node_modules. Strip any stray per-package node_modules a dev worktree's pnpm
  # may have left in the source so it can't shadow the hoisted root.
  postBunNodeModulesInstallPhase = ''
    hydrate() {
      local name="$1" dir="$2"
      local dest="node_modules/$name"
      mkdir -p "$(dirname "$dest")"
      rm -rf "$dest"
      cp -rL "${koluSrc}/packages/$dir" "$dest"
      chmod -R u+w "$dest"
      rm -rf "$dest/node_modules"
    }
    ${lib.concatStringsSep "\n    " (lib.mapAttrsToList
      (name: dir: "hydrate ${lib.escapeShellArg name} ${lib.escapeShellArg dir}")
      koluPackages)}
  '';

  # Ship the compiled bundle (NOT src — the runtime exec's dist/bin.js), the
  # node_modules the bundle resolves its `external` deps from at runtime (incl.
  # @opentui/core's per-arch native package), and package.json for its
  # `"type": "module"`.
  installPhase = ''
    runHook preInstall
    mkdir -p $out/lib/arivu-tui
    cp -rL dist $out/lib/arivu-tui/dist
    cp -r node_modules $out/lib/arivu-tui/
    cp package.json $out/lib/arivu-tui/
    runHook postInstall
  '';

  # Build-time smoke: run the INSTALLED bundle under Bun so a bad bundle, a
  # missing runtime dep, or a node-compat hole fails the Nix build here — not
  # silently at the user's first invocation. `--help` exits 0 before bin.ts
  # dynamically imports the OpenTUI renderer, so this proves the bundle loads and
  # runs under Bun without needing a TTY or the native lib (the native dlopen is
  # exercised by the real render, captured separately). Runs $out's exact tree
  # (dist/bin.js + the hydrated node_modules), the same file the wrapper exec's.
  doInstallCheck = true;
  installCheckPhase = ''
    runHook preInstallCheck
    ${bun}/bin/bun $out/lib/arivu-tui/dist/bin.js --help > /dev/null
    runHook postInstallCheck
  '';

  # `entryPath` is the single source of truth for the Bun entry the wrapper in
  # the repo-root `default.nix` exec's: installPhase produces it under this `$out`, and
  # the wrapper consumes `arivuTuiBuilt.entryPath` — one value, so the two files
  # cannot silently desync (no cross-file string to keep in step, no build-time
  # guard).
  passthru.entryPath = "${finalAttrs.finalPackage}/lib/arivu-tui/dist/bin.js";

  meta = {
    description = "arivu-tui viewer — Bun-built tree (viewer source + hydrated @kolu/* + node_modules)";
    platforms = lib.platforms.unix;
  };
})
