# Curated word lists for worktree branch name generation.
# Produces a JSON file with adjectives and nouns — short, pronounceable,
# and pleasant as branch names (e.g. "calm-brook", "vivid-mesa").
{ pkgs }:

pkgs.writeTextFile {
  name = "worktree-words";
  destination = "/words.json";
  text = builtins.toJSON {
    adjectives = [
      "amber"
      "bold"
      "calm"
      "crisp"
      "dark"
      "eager"
      "fair"
      "firm"
      "gentle"
      "grand"
      "happy"
      "hazy"
      "idle"
      "iron"
      "jade"
      "keen"
      "kind"
      "lean"
      "light"
      "mellow"
      "mild"
      "neat"
      "noble"
      "odd"
      "open"
      "plain"
      "proud"
      "pure"
      "quiet"
      "rapid"
      "rich"
      "safe"
      "sharp"
      "swift"
      "tall"
      "thin"
      "vast"
      "vivid"
      "warm"
      "wise"
      "young"
      "zesty"
      "bright"
      "clear"
      "deep"
      "fresh"
      "blue"
      "green"
    ];
    nouns = [
      "arch"
      "bay"
      "brook"
      "bluff"
      "canyon"
      "cliff"
      "cove"
      "creek"
      "dale"
      "delta"
      "dune"
      "elm"
      "fern"
      "field"
      "forge"
      "glen"
      "grove"
      "harbor"
      "heath"
      "hill"
      "inlet"
      "isle"
      "knoll"
      "lake"
      "ledge"
      "loft"
      "marsh"
      "mesa"
      "mist"
      "nook"
      "oak"
      "oasis"
      "peak"
      "plume"
      "pond"
      "reef"
      "ridge"
      "shade"
      "shore"
      "trail"
      "vale"
      "vista"
      "weald"
      "wood"
      "knot"
      "crest"
      "pass"
      "rill"
    ];
  };
}
