# arivu-tui viewer — Bun-built tree (arivu P3 PR1).
#
# Produces $out/lib/arivu-tui ready to be exec'd by the `bun` wrapper in
# `../../default.nix`. This is the one-level-up twin of drishti's Bun-on-Nix
# recipe (nix/packages/drishti-agent in srid/drishti): the dep cache comes from
# the committed `bun/bun.nix` via `bun2nix.fetchBunDeps` (per-tarball FODs, no
# network in the sandbox), and `@kolu/*` is HYDRATED from kolu's own source
# after `bun install`, never bun-installed.
#
# Why hydrate (not a bun workspace): the viewer reaches @kolu/arivu-contract,
# @kolu/surface and @kolu/surface-nix-host, and arivu-contract pulls in
# @kolu/terminal-awareness's ZOD-ONLY `/schema` entry. But terminal-awareness's
# full manifest declares anyagent/anyforge/kaval/kolu-* (node-pty and the whole
# sensor spine). A bun workspace would try to resolve that entire manifest;
# hydrating the SOURCE sidesteps it — only what the viewer actually imports at
# runtime matters, and the flat npm closure those sources resolve is declared in
# `bun/package.json`. This is exactly why drishti hydrates @kolu/surface too.
#
# `koluSrc` is kolu's shared `src` fileset (default.nix) — reused verbatim so
# this build's source closure matches the typecheck's, with no parallel fileset
# to drift. It carries packages/arivu-tui (the viewer) and the five hydrated
# @kolu packages.
{ stdenv, lib, bun, bun2nix, koluSrc }:
let
  # The Bun project root: the bun-facing manifest + lockfile + bunfig + the
  # autogenerated dep cache. Kept under nix/ (OUTSIDE packages/**) so pnpm —
  # whose workspace is packages/** — never sees this second package.json.
  src = lib.fileset.toSource {
    root = ./bun;
    fileset = lib.fileset.unions [
      ./bun/package.json
      ./bun/bun.lock
      ./bun/bunfig.toml
      ./bun/bun.nix
    ];
  };
  # The workspace closure to hydrate, as `package-name → source dir under
  # packages/`. This is the COMPLETE runtime set the viewer resolves under Bun,
  # established empirically (`bun src/bin.ts list` reaches its socket-connect
  # step with every module resolved): the @kolu/surface stack, plus the
  # vendor-neutral schema packages `@kolu/arivu-contract` composes
  # `AwarenessValue` from — `terminal-awareness/schema` pulls anyforge/kolu-git/
  # kolu-{github,claude-code,codex,opencode}'s `/schemas`, and those agent
  # schemas pull `anyagent`'s barrel. Each is reached only through a zod-only
  # `/schemas` (or anyagent's light index) entry, so their heavy `.` deps
  # (@anthropic SDK, simple-git, @parcel/watcher) never load — which is exactly
  # why hydrating the SOURCE beats a bun workspace that would resolve the whole
  # manifest. Integration packages live under packages/integrations/<dir> with a
  # name that differs from the dir, so this is a map, not a flat list.
  koluPackages = {
    "@kolu/arivu-contract" = "arivu-contract";
    "@kolu/surface" = "surface";
    "@kolu/surface-nix-host" = "surface-nix-host";
    "@kolu/terminal-awareness" = "terminal-awareness";
    "@kolu/shell-quote" = "shell-quote";
    "anyagent" = "integrations/anyagent";
    "anyforge" = "integrations/anyforge";
    "kolu-git" = "integrations/git";
    "kolu-github" = "integrations/github";
    "kolu-claude-code" = "integrations/claude-code";
    "kolu-codex" = "integrations/codex";
    "kolu-opencode" = "integrations/opencode";
  };
in
stdenv.mkDerivation {
  pname = "arivu-tui-built";
  version = "0.1.0";
  inherit src;

  # Our npins-pinned bun wins on PATH over bun2nix.hook's propagated bun, for a
  # reproducible install across linux-x64 and darwin-arm64 (drishti's rationale).
  nativeBuildInputs = [ bun bun2nix.hook ];

  bunDeps = bun2nix.fetchBunDeps {
    bunNix = ./bun/bun.nix;
  };

  # Hoisted linker matches bunfig.toml: the hydrated @kolu/* sources carry no
  # node_modules of their own, so they must resolve @orpc/*, zod and solid-js
  # from one root node_modules.
  bunInstallFlags = [ "--linker=hoisted" ];

  # Pure overhead for a Bun app — no shebangs we care about, no native binaries.
  dontFixup = true;
  dontPatchShebangs = true;

  # No client bundle in PR1 — the viewer runs its TS source directly under Bun
  # (today's columnify text output, behaviour-preserving). PR2 adds the OpenTUI
  # bundle here.
  dontUseBunBuild = true;
  dontBuild = true;

  # @kolu/* are Nix-store sources, not bun.lock entries — drop them into
  # node_modules AFTER bun install populates it. cp -rL (not symlink): the
  # hydrated sources resolve their transitive imports from the *real* file
  # location, so they must sit at a path whose ancestor is the hoisted root
  # node_modules. Strip any stray per-package node_modules a dev worktree's pnpm
  # may have left in the source so it can't shadow the hoisted root.
  postBunNodeModulesInstallPhase = ''
    hydrate() {
      local name="$1" dir="$2"
      local dest="node_modules/$name"
      mkdir -p "$(dirname "$dest")"
      rm -rf "$dest"
      cp -rL "${koluSrc}/packages/$dir" "$dest"
      chmod -R u+w "$dest"
      rm -rf "$dest/node_modules"
    }
    ${lib.concatStringsSep "\n    " (lib.mapAttrsToList
      (name: dir: "hydrate ${lib.escapeShellArg name} ${lib.escapeShellArg dir}")
      koluPackages)}
  '';

  installPhase = ''
    runHook preInstall
    mkdir -p $out/lib/arivu-tui
    cp -rL ${koluSrc}/packages/arivu-tui/src $out/lib/arivu-tui/src
    cp -r node_modules $out/lib/arivu-tui/
    cp package.json bunfig.toml $out/lib/arivu-tui/
    # Guard: the wrapper in ../../default.nix hard-codes this entry path. Fail
    # the build (not runtime) if it moves.
    entry="$out/lib/arivu-tui/src/bin.ts"
    test -e "$entry" || {
      echo "installPhase: $entry missing — update ../../default.nix if the path changed"
      exit 1
    }
    runHook postInstall
  '';

  meta = {
    description = "arivu-tui viewer — Bun-built tree (viewer source + hydrated @kolu/* + node_modules)";
    platforms = lib.platforms.unix;
  };
}
