# Nix derivation that fetches and bundles all web font assets.
# DM Sans (variable weight 400–600) from Google Fonts, FiraCode Nerd Font from nerdfont-webfonts.
#
# Outputs:
#   $out/*.woff2   — font files (copied into client/public/fonts/ at build time)
#   $out/fonts.css — @font-face declarations (imported via vite alias "kolu-fonts")
{ pkgs }:
let
  fetchFont = name: url: hash:
    pkgs.fetchurl { inherit url hash; inherit name; };

  # Each entry: { subset, url, hash, unicodeRange }
  dmSansSubsets = [
    {
      subset = "latin-ext";
      url = "https://fonts.gstatic.com/s/dmsans/v17/rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu6-K6h9Q.woff2";
      hash = "sha256-pdOP6Z+TAnVoSZm0YscSP6oGPZ5E5ztLJBcj2ISqD0k=";
      unicodeRange = "U+0100-02BA, U+02BD-02C5, U+02C7-02CC, U+02CE-02D7, U+02DD-02FF, U+0304, U+0308, U+0329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF";
    }
    {
      subset = "latin";
      url = "https://fonts.gstatic.com/s/dmsans/v17/rP2Yp2ywxg089UriI5-g4vlH9VoD8Cmcqbu0-K4.woff2";
      hash = "sha256-n+pgipR+ZwIMM8rZpv49YMVBGd+4z/h3aKgRehXtdUM=";
      unicodeRange = "U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA, U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD";
    }
  ];

  firacode = [
    (fetchFont "FiraCodeNerdFont-Regular.woff2"
      "https://cdn.jsdelivr.net/gh/mshaugh/nerdfont-webfonts@v3.3.0/build/fonts/FiraCodeNerdFont-Regular.woff2"
      "sha256-71OZLN9GnUAk0u/CnVHAWmVCXRymkOUF+rgCI5gKBn0=")
    (fetchFont "FiraCodeNerdFont-Bold.woff2"
      "https://cdn.jsdelivr.net/gh/mshaugh/nerdfont-webfonts@v3.3.0/build/fonts/FiraCodeNerdFont-Bold.woff2"
      "sha256-7LYtNpPVIeYD1I6Jeb9bdOB2/vOjfnrSPD3l4SMMgzs=")
  ];

  allFonts = map (s: fetchFont "dm-sans-${s.subset}.woff2" s.url s.hash) dmSansSubsets ++ firacode;

  # Generate @font-face CSS. URLs use /fonts/ (absolute) so they resolve
  # correctly whether the CSS is loaded via vite alias or from the public dir.
  dmSansFaces = builtins.concatStringsSep "\n" (map
    (s: ''
      /* ${s.subset} */
      @font-face {
        font-family: "DM Sans";
        font-style: normal;
        font-weight: 400 600;
        font-display: swap;
        src: url("/fonts/dm-sans-${s.subset}.woff2") format("woff2");
        unicode-range: ${s.unicodeRange};
      }
    '')
    dmSansSubsets);

  fontsCss = ''
    /* Auto-generated by nix/packages/fonts — do not edit manually */
    ${dmSansFaces}
    @font-face {
      font-family: "FiraCode Nerd Font";
      font-style: normal;
      font-weight: 400;
      font-display: swap;
      src: url("/fonts/FiraCodeNerdFont-Regular.woff2") format("woff2");
    }

    @font-face {
      font-family: "FiraCode Nerd Font";
      font-style: normal;
      font-weight: 700;
      font-display: swap;
      src: url("/fonts/FiraCodeNerdFont-Bold.woff2") format("woff2");
    }
  '';
in
pkgs.runCommand "kolu-fonts" { } ''
  mkdir -p $out
  ${pkgs.lib.concatMapStringsSep "\n" (f: "cp ${f} $out/${f.name}") allFonts}
  cat > $out/fonts.css << 'ENDCSS'
  ${fontsCss}
  ENDCSS
''
