name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  local-checks:
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - run: just ci::fmt ci::typecheck ci::unit ci::apm-sync

  nix:
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - run: just ci::nix

  e2e:
    needs: nix
    runs-on: ${{ matrix.system }}
    strategy:
      matrix:
        system: [x86_64-linux, aarch64-darwin]
    steps:
      - uses: actions/checkout@v4
      - run: just ci::e2e

  home-manager:
    needs: nix
    runs-on: x86_64-linux
    steps:
      - uses: actions/checkout@v4
      - run: just ci::home-manager
